name: CI
on: [push]  
jobs:
  test:
    runs-on: ubuntu-latest
    name: CRDA Scan
    steps: 
      - name: Checkout
        uses: actions/checkout@v2
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: crda.sarif
      - name: Save Intermediate files
        run: |  
          mkdir -p uploads
          mv crda.sarif uploads 
      - name: Upload merged Results  
        uses: actions/upload-artifact@v2
        with: 
          name: workfiles
          path: ./uploads
